inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  DisplayCopNames: true

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'app/controllers/catalog_controller.rb'
    - 'config/initializers/devise.rb'

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/controllers/catalog_controller.rb' # holds a long bl configuration

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /\.rake$/
    - 'app/controllers/catalog_controller.rb' # holds a long bl configuration
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# Exclude generated code and specs
Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/models/solr_document.rb'
    - 'app/models/application_record.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/user.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/search_history_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'
    - 'spec/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
