ars:
  name: 'Archive of Recorded Sound'
  visit_note: 'The Archive’s materials are for on-site use only. It is advised that visitors contact the Archive in advance so that required materials can be prepared.'
  description: 'The Archive of Recorded Sound’s collection contains over 400,000 items that span sound recording history--from its beginnings to the present day. Nearly all formats ever developed to record sound are represented: piano rolls; wax cylinders; shellac, acetate, aluminum, and vinyl discs; magnetic wire and tape recordings; compact discs. Collections are particularly strong in the areas of jazz and opera.'
  building: 'Braun Music Center'
  address1: '541 Lasuen Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305-3076'
  country: 'USA'
  phone: ''
  contact_info: 'soundarchive@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/branch/image/Edison_002LowRes.jpg'

speccol:
  name: 'Special Collections'
  visit_note: 'Special Collections and University Archives materials are stored offsite and must be paged 36 hours in advance.'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  building: 'Green Library'
  address1: '557 Escondido Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305'
  country: 'USA'
  phone: '(650) 725-1022'
  contact_info: 'specialcollections@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/branch/image/DSC_0011_150.jpg'

uarc:
  name: 'University Archives'
  visit_note: 'Special Collections and University Archives materials are stored offsite and must be paged 36 hours in advance.'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  building: 'Green Library'
  address1: '557 Escondido Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305'
  country: 'USA'
  phone: '(650) 725-1022'
  contact_info: 'specialcollections@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/branch/image/DSC_0011_150.jpg'
