aspace:
  url: <%= ENV['ASPACE_URL'] || 'http://archivesspace-stage.stanford.edu:8081' %>
  harvestable_repository_codes:
    - ars
    - cubberley
    - eal
    - speccoll
data_dir: <%= ENV['DATA_DIR'] || './spec/fixtures/ead' %>
