hours_api: 'https://library-hours.stanford.edu/'

featured_items:
  - image_url: https://stacks.stanford.edu/image/iiif/qy843rv0944/qy843rv0944_0080/200,700,2000,2500/!800,800/0/default.jpg
    image_alt: USA Exhibit 388, Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-46
    caption_html: USA Exhibit 388, Taube Archive of the International Military Tribunal (IMT) at Nuremberg, 1945-46
  - image_url: https://stacks.stanford.edu/image/iiif/gs873gr6640/gs873gr6640_0001/full/!800,800/0/default.jpg
    image_alt: Crucifix, Fear, from Lynn Beldner Punk Music Photograph Collection
    caption_html: Crucifix, Fear, Lynn Beldner Punk Music Photograph Collection
  - image_url: https://stacks.stanford.edu/image/iiif/xc332sx6392/xc332sx6392_0001/full/!800,800/0/default.jpg
    image_alt: Monterey Jazz Festival Program. 1972, Programs, 1958-2019; 2021
    caption_html: Monterey Jazz Festival Program. 1972, Programs, 1958-2019; 2021

# Locations with a 'closed_note' will display the note in lieu of fetching hours from the API.
hours_locations:
  - label: 'Green Library, 2nd Floor'
    library: 'spc'
    location: 'field-reading-room'
    url: 'https://library.stanford.edu/libraries/special-collections'
  - label: 'Archive of Recorded Sound'
    library: 'ars'
    location: 'archive-recorded-sound'
    url: 'https://library.stanford.edu/libraries/archive-recorded-sound'
  - label: 'Cubberley Education Library'
    library: 'cubberley'
    location: 'library-circulation'
    url: 'https://library.stanford.edu/libraries/cubberley-education-library'
    closed_note: 'Closed until 2025'
  - label: 'East Asia Library'
    library: 'eal'
    location: 'library-circulation'
    url: 'https://library.stanford.edu/libraries/east-asia-library'

aspace:
  url: <%= ENV['ASPACE_URL'] || 'http://archivesspace-stage.stanford.edu:8081' %>
  harvestable_repository_codes:
    - ars
    - cubberley
    - eal
    - mhc
    - speccoll
data_dir: <%= ENV['DATA_DIR'] || './spec/fixtures/ead' %>

pdf_generation:
  create_on_ead_download: true
  ead_to_fo_xsl_path: './app/xslt/ead_to_fo.xsl'
  fop_config_path: './config/pdf_generation/fop-config.xml'
  fop_path: 'fop'
  logo_path: './app/assets/images/sul-logo-bw_lightbackground.png'
  saxon_path: '/opt/app/arclight/SaxonHE12-4J/saxon-he-12.4.jar'